// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgjfjbvvfvraqgfnysyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnamZqYnZ2ZnZyYXFnZm55c3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzAzNzAsImV4cCI6MjA2NTU0NjM3MH0.ucr2XS53AAeaN_TJbKqj9hnYp-s26RASH3WBA0Ej1SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);